language: node_js
cache: npm
node_js:
  - "8"
addons:
  chrome: stable
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: check for updates
      script:
        - node ./op-update-watcher/checkVersionAndPush.js
      on:
        branch:
          - feature/automatic-updates
          - master
    - stage: publish
      script: false
      deploy:
        provider: script
        script:
          - npm run semantic-release
        skip_cleanup: true
        on:
          branch:
            - master
