language: node_js
cache:
  npm: true
  directories:
    - /tmp/chromedriver/
node_js:
  - "8"
addons:
  chrome: stable
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_script:
  - npm install -g chromedriver@2.46.0
jobs:
  include:
    - stage: check for updates
      script:
        - node ./op-update-watcher/checkVersionAndPush.js
      on:
        branch:
          - master
    - stage: publish
      script: false
      deploy:
        provider: script
        script:
          - npm run semantic-release
        skip_cleanup: true
        on:
          branch:
            - master
