language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: publish
      script: false
      deploy:
        provider: script
        script:
          - npm run semantic-release --dry-run
        skip_cleanup: true
        on:
          branch:
            - master
            - feature/release-automation
